### ISSUE TITLE
MAIN.PY RUN ISSUE

### ISSUE THREAD

**Issue by mangeshsable1975** [dipakgmx/NSEOPTParser#1]
![ERROR](https://user-images.githubusercontent.com/67979855/140653281-836e6a9f-df30-407c-8724-173f7e77d429.jpg)

**Comment by dipakgmx** [comment]
Parsing would only be performed between [08:55 hrs and 15:35 hrs](https://github.com/dipakgmx/NSEOPTParser/blob/5dd96e18d3e72398d883450a96aafed85516607b/URLParser.py#L40).
